#!/bin/sh

rebuild_command=$(/bin/ls /nix/store/*-darwin-rebuild/bin/darwin-rebuild | head -n 1)

cd ${HOME}/.config/nix
git pull

alejandra . &> /dev/null

git add .
${rebuild_command} switch --flake .#Nicks-MacBook-Pro

machine=macbook_pro
gen=$(${rebuild_command} --list-generations | grep current)
date=$(date)
git commit -m "$machine_$gen_$date"
git push
